/**
 * Shared dox-field constants used by the file-first wizard steps.
 *
 * This module is a thin re-export on top of `shared/fieldMappings.ts` so the
 * wizard and the backend both agree on which core fields exist, what their
 * default aliases look like, and which target options are offered in the
 * Schema Review dropdowns.
 *
 * Do NOT redefine the core field list here — always extend
 * `shared/fieldMappings.ts` and re-export.
 */

import {
  CORE_FIELD_DEFINITIONS,
  CORE_FIELD_KEYS,
  defaultFieldMappings,
  normalizeFieldMappings,
  validateFieldMappings,
  type CoreFieldKey,
  type CoreFieldDefinition,
  type ConnectorFieldMappings,
  type FieldMappingCore,
  type FieldMappingExtended,
} from '../../../shared/fieldMappings';

export {
  CORE_FIELD_DEFINITIONS,
  CORE_FIELD_KEYS,
  defaultFieldMappings,
  normalizeFieldMappings,
  validateFieldMappings,
};

export type {
  CoreFieldKey,
  CoreFieldDefinition,
  ConnectorFieldMappings,
  FieldMappingCore,
  FieldMappingExtended,
};

/** Quick label lookup for UI rendering. Keyed by CoreFieldKey. */
export const DOX_FIELD_LABELS: Record<CoreFieldKey, string> = CORE_FIELD_DEFINITIONS.reduce(
  (acc, def) => {
    acc[def.key] = def.label;
    return acc;
  },
  {} as Record<CoreFieldKey, string>,
);

/** Special sentinel used in the schema-review dropdown for "promote this column to extended metadata". */
export const TARGET_EXTENDED = '__extended__';
/** Special sentinel used in the schema-review dropdown for "skip this column entirely". */
export const TARGET_IGNORE = '__ignore__';

export type TargetOption = CoreFieldKey | typeof TARGET_EXTENDED | typeof TARGET_IGNORE;

/**
 * Full option list shown in the "Map to" dropdown for each detected source
 * field. Core field keys come first, then the two sentinel options.
 */
export const TARGET_OPTIONS: readonly TargetOption[] = [
  ...CORE_FIELD_KEYS,
  TARGET_EXTENDED,
  TARGET_IGNORE,
];

/**
 * Human-readable label for any TargetOption (core key or sentinel).
 */
export function targetOptionLabel(option: TargetOption): string {
  if (option === TARGET_EXTENDED) return 'Add as extended field';
  if (option === TARGET_IGNORE) return 'Ignore this column';
  return DOX_FIELD_LABELS[option];
}

/**
 * Convert an arbitrary source column name into a snake_case key suitable for
 * `extended_metadata`. Lowercases, strips non-alphanumerics, collapses runs
 * of underscores. "Ship Date" -> "ship_date", "Cust #" -> "cust",
 * "   " -> "".
 *
 * Matches the helper used by the backend's schemaDiscovery module so keys
 * generated by the wizard stay stable if the user re-discovers the schema.
 */
export function toSnakeCase(source: string): string {
  return source
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .replace(/_+/g, '_');
}

/**
 * Check whether a target string is one of the canonical core-field keys.
 */
export function isCoreFieldKey(target: string): target is CoreFieldKey {
  return (CORE_FIELD_KEYS as readonly string[]).includes(target);
}
