// Re-export frontend-friendly types from shared
export type { Role, DocumentStatus } from '../../shared/types';
export type { User, Tenant, Document, DocumentVersion, AuthPayload } from '../../shared/types';
export type {
  ApiDocument,
  ApiDocumentVersion,
  ApiUser,
  ApiTenant,
  ApiAuditEntry,
  ApiProduct,
  ApiDocumentType,
  LoginResponse,
  RegisterResponse,
  DocumentListResponse,
  DocumentGetResponse,
  DocumentCreateResponse,
  DocumentUpdateResponse,
  DocumentVersionsResponse,
  DocumentUploadResponse,
  SearchResponse,
  AuditListResponse,
  ResetPasswordResponse,
  IngestResponse,
  LookupResponse,
  ProductListResponse,
  ProductGetResponse,
  DocumentTypeListResponse,
  DocumentTypeGetResponse,
  ApiKey,
  CreateApiKeyResponse,
  ApiDocumentProduct,
  DocumentProductListResponse,
  ExtractionField,
  ExpirationListResponse,
  ExpirationItem,
  ExpirationSummary,
  ApiBundle,
  ApiBundleItem,
  BundleListResponse,
  BundleGetResponse,
  ProcessingResult,
  ProcessingResponse,
  ExtractedTable,
  ExtractionExampleRow,
  ProcessingQueueItem,
  QueuedResponse,
  ParsedQuery,
  NaturalSearchResponse,
  ApiSupplier,
  SupplierListResponse,
  SupplierGetResponse,
  SupplierLookupOrCreateResponse,
} from '../../shared/types';
export { AUTH_TOKEN_KEY, AUTH_USER_KEY } from '../../shared/types';
