// Import types used locally in this file
import type { TemplateFieldMapping } from '../../shared/types';

// Re-export frontend-friendly types from shared
export type { Role, DocumentStatus, RenewalType, ApiDocumentCategory } from '../../shared/types';
export type { User, Tenant, Document, DocumentVersion, AuthPayload, Assignment } from '../../shared/types';
export type {
  ApiDocument,
  ApiDocumentVersion,
  ApiUser,
  ApiTenant,
  ApiAuditEntry,
  ApiProduct,
  ApiDocumentType,
  LoginResponse,
  RegisterResponse,
  DocumentListResponse,
  DocumentGetResponse,
  DocumentLinkedLot,
  DocumentCreateResponse,
  DocumentUpdateResponse,
  DocumentVersionsResponse,
  DocumentUploadResponse,
  SearchResponse,
  AuditListResponse,
  ResetPasswordResponse,
  IngestResponse,
  LookupResponse,
  ProductListResponse,
  ProductGetResponse,
  DocumentTypeListResponse,
  DocumentTypeGetResponse,
  // Registry vocabulary admin (migration 0080)
  ApiRequirement,
  ApiClaimType,
  ApiClaimRule,
  ClaimSubjectGrain,
  RequirementListResponse,
  RequirementGetResponse,
  ClaimTypeListResponse,
  ClaimTypeGetResponse,
  ClaimRuleListResponse,
  ApiKey,
  CreateApiKeyResponse,
  ApiDocumentProduct,
  DocumentProductListResponse,
  ApiBundle,
  ApiBundleItem,
  BundleListResponse,
  BundleGetResponse,
  ProcessingResult,
  ProcessingResponse,
  ExtractedTable,
  ProductEntry,
  ExtractionExampleRow,
  ProcessingQueueItem,
  QueuedResponse,
  ParsedQuery,
  NaturalSearchResponse,
  OrderNaturalSearchResponse,
  ApiSupplier,
  SupplierListResponse,
  SupplierGetResponse,
  SupplierLookupOrCreateResponse,
  SupplierDuplicateMember,
  SupplierDuplicateCluster,
  SupplierDuplicatesResponse,
  SupplierMergeResponse,
  SupplierRow,
  LotScheme,
  ProductMapEntry,
  OrderProductOption,
  ProductMapGetResponse,
  ProductMapPutResponse,
  OrderProductListResponse,
  TemplateFieldMapping,
  ExtractionTemplateRow,
  SupplierExtractionInstructions,
  SupplierExtractionInstructionsGetResponse,
  SupplierExtractionInstructionsPutResponse,
  SupplierExtractionInstructionsListRow,
  SupplierExtractionInstructionsListResponse,
  TeachSession,
  TeachMessage,
  TeachExample,
  TeachProposal,
  TeachSessionStatus,
  TeachMessageRole,
  TeachSessionCreateResponse,
  TeachMessageResponse,
  TeachSynthesizeResponse,
  TeachSessionDetailResponse,
  TeachConfirmResponse,
  TeachSessionSummary,
  TeachSessionListResponse,
  ActivityEvent,
  ActivityEventType,
  ActivitySourceFilter,
  ActivityStatusFilter,
  ActivityConnectorRunEvent,
  ActivityDocumentIngestEvent,
  ActivityOrderCreatedEvent,
  ActivityAuditEvent,
  ActivityFilters,
  ActivityListResponse,
  ActivityEventDetailResponse,
  SavedSearch,
  CreateSavedSearchRequest,
  UpdateSavedSearchRequest,
  SavedSearchListResponse,
  SavedSearchResponse,
  UniversalSearchParams,
  UniversalSearchResponse,
  UniversalSearchBlock,
  UniversalSearchDocument,
  UniversalSearchSupplier,
  UniversalSearchProduct,
  UniversalSearchDocType,
  UniversalSearchOrder,
  UniversalSearchCustomer,
  UniversalSearchBundle,
  LotListItem,
  LotListResponse,
  LotCoaDocument,
  LotOrderLine,
  LotSuggestion,
  LotDetail,
  CoaGapStatus,
  CoaAvailability,
  CoaFulfillmentRow,
  CoaFulfillmentSummary,
  CoaFulfillmentResponse,
  ExpirationStatus,
  ExpirationRow,
  ExpirationSummary,
  ExpirationListResponse,
  ExpirationNotifyResponse,
  LotMatchSuggestion,
  LotMatchListResponse,
  CoaRecordCardinality,
  CoaRecordKeyBasis,
  CoaResultCell,
  CoaRecord,
  CoaRecordsPayload,
  CoaRecordDecision,
} from '../../shared/types';
export { AUTH_TOKEN_KEY, AUTH_USER_KEY } from '../../shared/types';
export { parseCoaRecords } from '../../shared/types';

export interface ExtractionTemplate {
  id: string;
  tenant_id: string;
  supplier_id: string;
  document_type_id: string;
  field_mappings: TemplateFieldMapping[];
  auto_ingest_enabled: number;
  confidence_threshold: number;
  created_by: string | null;
  created_at: string;
  updated_at: string;
  supplier_name?: string;
  document_type_name?: string;
}
