/**
 * WHICH ORGANISATIONS A SHIPPED CHANGE ACTUALLY REACHES.
 *
 * AJ Conner, reviewing v2.7.0-v2.20.0: "Mark in each release which changes
 * reach existing tenants and which only land on new ones. The GFSI change is
 * right ... but it applies to newly set-up orgs only, so our config keeps the
 * old rule. That is the first product default to drift from our tenant and it
 * will not be the last."
 *
 * He is describing a class of bug that release notes create rather than
 * report. Three things ship under the same heading and read identically:
 *
 *   1. A migration plus code. Everybody has it tomorrow morning.
 *   2. A changed DEFAULT in a starter pack. Only an organisation set up after
 *      today gets it; the live tenant keeps whatever it was seeded with, and
 *      nothing in the app will ever say the two disagree.
 *   3. A feature that exists and does nothing until an admin configures it.
 *
 * A reader who cannot tell them apart will either expect a change that never
 * arrives or, worse, believe their configuration matches a default it has
 * quietly diverged from. So every bullet declares which it is.
 *
 * WHY A LEADING TOKEN IN THE MARKDOWN and not frontmatter. Release notes are
 * written by a person in an editor, at the end of a long day, in the file
 * `bin/release` just opened for them. A frontmatter list would have to name
 * bullets by index and would rot the first time one was reordered; a token at
 * the head of the bullet it describes cannot drift from its bullet, survives
 * copy-paste, and is legible as plain text in `git show` with no renderer.
 * `bin/release` refuses to cut a release whose notes carry none, so the
 * question is answered every time rather than remembered.
 *
 * THE VOCABULARY LIVES HERE AND NOWHERE ELSE. The in-app renderer imports it;
 * `bin/release` reads the esbuild mirror (`bin/lib/shared/releaseReach.js`,
 * generated by `npm run build:worker-shared`), so the guard and the chip can
 * never recognise different words.
 */

/** The three answers, in the order they appear on a release page. */
export const RELEASE_REACH_TOKENS = ['existing', 'new-orgs', 'config'] as const;

export type ReleaseReach = (typeof RELEASE_REACH_TOKENS)[number];

/** The chip's words. Deliberately a full claim, not a category name. */
export const RELEASE_REACH_LABEL: Record<ReleaseReach, string> = {
  existing: 'Reaches every organisation now',
  'new-orgs': 'New organisations only',
  config: 'Needs configuration',
};

/** The sentence behind the chip — shown as its tooltip. */
export const RELEASE_REACH_HELP: Record<ReleaseReach, string> = {
  existing:
    'Live for every organisation as soon as this release is deployed. Nobody has to do anything.',
  'new-orgs':
    'A changed default that is applied when an organisation is first set up. Organisations configured before this release keep the configuration they already have — it is not rewritten, and it will not match the new default.',
  config:
    'Shipped, but inert until somebody sets it up. Nothing about how your organisation behaves today changes on its own.',
};

/** MUI chip colours. `new-orgs` is the one worth a second look, so it warns. */
export const RELEASE_REACH_COLOR: Record<ReleaseReach, 'success' | 'warning' | 'info'> = {
  existing: 'success',
  'new-orgs': 'warning',
  config: 'info',
};

/**
 * The token as it is written: `[existing]` at the very start of a bullet or a
 * paragraph. Built from the vocabulary above so adding a fourth answer cannot
 * leave the matcher behind.
 */
export const RELEASE_REACH_PATTERN = new RegExp(
  `^\\[(${RELEASE_REACH_TOKENS.join('|')})\\]\\s*`,
);

export function isReleaseReach(value: unknown): value is ReleaseReach {
  return typeof value === 'string' && (RELEASE_REACH_TOKENS as readonly string[]).includes(value);
}

/**
 * Split a leading marker off a line of text.
 *
 * Returns `reach: null` and the text untouched when there is none — an
 * unmarked bullet renders exactly as it always did, which is what keeps this
 * convention safe to introduce on notes written before it existed.
 */
export function splitReachToken(text: string): { reach: ReleaseReach | null; rest: string } {
  const m = RELEASE_REACH_PATTERN.exec(text);
  if (!m) return { reach: null, rest: text };
  const reach = m[1];
  return isReleaseReach(reach) ? { reach, rest: text.slice(m[0].length) } : { reach: null, rest: text };
}

/**
 * Does this release-notes document declare the reach of anything at all?
 *
 * THIS IS THE GUARD `bin/release` USES, and it is deliberately a low bar: one
 * marker anywhere. The alternative — insisting every bullet carry one — would
 * be enforced by a script against prose a human is still writing, and the
 * predictable outcome is a `--no-verify` equivalent that gets used every time.
 * One marker means somebody thought about the question; the review is where
 * the rest is caught.
 *
 * HTML comments are stripped first: the draft `bin/release` generates carries
 * the instructions for this convention as a comment, and a guard satisfied by
 * its own instructions would pass on every release forever.
 */
export function hasReachMarker(markdown: string): boolean {
  const withoutComments = markdown.replace(/<!--[\s\S]*?-->/g, '');
  return withoutComments
    .split('\n')
    .some((line) => RELEASE_REACH_PATTERN.test(line.replace(/^\s*(?:[-*+]|\d+\.)\s+/, '')));
}
