/**
 * The frozen copy of a limit that gets stored alongside a verdict.
 *
 * WHY THIS IS ITS OWN MODULE. It used to live inside
 * functions/lib/spec-register.ts, where it had exactly one caller: the approval
 * path. `bin/backfill-spec-register` is a second producer of register rows, and
 * a backfilled row has to be re-explainable in a year on exactly the same terms
 * as an approval-written one — same keys, same values, same omissions. Two
 * copies of this function would be two answers to "what was this judged
 * against?", and the drift would be invisible until somebody read a snapshot
 * from the wrong year. So there is one function, the Workers runtime imports it
 * directly, and bin/ imports the esbuild bundle of this file
 * (`bin/lib/shared/specSnapshot.js`, generated by `npm run build:worker-shared`).
 *
 * THE UNIT EQUIVALENCE BELONGS IN HERE, and it is not a detail. When a tenant
 * has said CFU/mL may be judged as CFU/g (migration 0093), the thing a result
 * was actually judged against is not "≤20000 CFU/g" — it is "≤20000 CFU/g, with
 * a millilitre basis accepted as a gram basis". Someone can turn that setting
 * off next month, and document_spec_checks exists precisely so that moving a
 * threshold cannot rewrite history; a snapshot that omitted the equivalence
 * would leave a verdict that can no longer be re-explained, or worse, one that
 * looks like it was reached under rules that were never applied to it.
 *
 * Recorded only when it was actually USED on this row (`unit_equivalence`
 * absent = the units lined up on their own). The verdict's `reason` says the
 * same thing in words and is stored beside it, so the record reads correctly
 * whether a person or a query is doing the reading.
 *
 * SO DOES THE CRITICALITY (migration 0095). It does not decide the verdict, but
 * it decided how loudly the verdict was PUT IN FRONT OF SOMEBODY, and that is
 * half of what a reader months later is trying to reconstruct: "this failed and
 * nobody chased it" reads very differently once you can see it was filed as a
 * tracked parameter at the time. Ranks get re-tuned exactly like thresholds do,
 * so the same freeze argument applies — a pointer to today's tier would rewrite
 * that history the moment someone promoted the limit.
 */

import type { SpecVerdict, ConfiguredLimit } from './specCheck';
import { parseSpecCriticality } from './specCriticality';

/**
 * Build the JSON that goes into `document_spec_checks.limit_snapshot`, or NULL
 * when there is nothing to freeze.
 *
 * `limits` is the set of configured limits the verdict was produced from; a
 * verdict whose `limit_id` is not in it falls back to the printed shape rather
 * than inventing numbers.
 */
export function buildLimitSnapshot(
  verdict: SpecVerdict,
  limits: ConfiguredLimit[]
): string | null {
  const equated = verdict.unit_equivalence_applied ? { unit_equivalence: 'volume_mass' } : {};
  if (verdict.source !== 'limit' || !verdict.limit_id) {
    // A printed-spec verdict's "limit" is the document's own text, which is
    // already captured verbatim in limit_text.
    return verdict.limit_text
      ? JSON.stringify({ printed: verdict.limit_text, ...equated })
      : null;
  }
  const l = limits.find((x) => x.id === verdict.limit_id);
  if (!l) {
    return verdict.limit_text
      ? JSON.stringify({ printed: verdict.limit_text, ...equated })
      : null;
  }
  return JSON.stringify({
    operator: l.operator,
    value_min: l.value_min,
    value_max: l.value_max,
    unit: l.unit,
    severity: l.severity,
    criticality: parseSpecCriticality(l.criticality),
    text: verdict.limit_text,
    ...equated,
  });
}
