/**
 * The frozen copy of a limit that gets stored alongside a verdict.
 *
 * WHY THIS IS ITS OWN MODULE. It used to live inside
 * functions/lib/spec-register.ts, where it had exactly one caller: the approval
 * path. `bin/backfill-spec-register` is a second producer of register rows, and
 * a backfilled row has to be re-explainable in a year on exactly the same terms
 * as an approval-written one — same keys, same values, same omissions. Two
 * copies of this function would be two answers to "what was this judged
 * against?", and the drift would be invisible until somebody read a snapshot
 * from the wrong year. So there is one function, the Workers runtime imports it
 * directly, and bin/ imports the esbuild bundle of this file
 * (`bin/lib/shared/specSnapshot.js`, generated by `npm run build:worker-shared`).
 *
 * THE UNIT EQUIVALENCE BELONGS IN HERE, and it is not a detail. When a tenant
 * has said CFU/mL may be judged as CFU/g (migration 0093), the thing a result
 * was actually judged against is not "≤20000 CFU/g" — it is "≤20000 CFU/g, with
 * a millilitre basis accepted as a gram basis". Someone can turn that setting
 * off next month, and document_spec_checks exists precisely so that moving a
 * threshold cannot rewrite history; a snapshot that omitted the equivalence
 * would leave a verdict that can no longer be re-explained, or worse, one that
 * looks like it was reached under rules that were never applied to it.
 *
 * Recorded only when it was actually USED on this row (`unit_equivalence`
 * absent = the units lined up on their own). The verdict's `reason` says the
 * same thing in words and is stored beside it, so the record reads correctly
 * whether a person or a query is doing the reading.
 *
 * SO DOES THE CRITICALITY (migration 0095). It does not decide the verdict, but
 * it decided how loudly the verdict was PUT IN FRONT OF SOMEBODY, and that is
 * half of what a reader months later is trying to reconstruct: "this failed and
 * nobody chased it" reads very differently once you can see it was filed as a
 * tracked parameter at the time. Ranks get re-tuned exactly like thresholds do,
 * so the same freeze argument applies — a pointer to today's tier would rewrite
 * that history the moment someone promoted the limit.
 */

import type { SpecVerdict, ConfiguredLimit } from './specCheck';
import { specResultKey } from './specCheck';
import { parseSpecCriticality } from './specCriticality';

/**
 * WHICH RESULT a register row is about (migration 0105), in the two forms the
 * register stores: the engine's own location key, and that location in words.
 *
 * Lives beside `buildLimitSnapshot` for the same reason that does: both
 * producers of register rows write it, and a backfilled row has to name its
 * result on exactly the same terms as an approval-written one.
 *
 * WHY IT EXISTS. A multi-lot COA prints one crosstab row per lot, and five lots
 * that each read "Coliform <10" are five genuine results that agree in every
 * column the register used to store. Measured on production they looked like
 * 53 duplicate groups; replaying the engine placed every row at a distinct row
 * or table. The location is the only thing that tells them apart, so it is
 * frozen with the verdict rather than re-derived from metadata that can change.
 */
export interface RegisterIdentity {
  /** `specResultKey(scope, target)` verbatim, e.g. "ai_fields::t0r2c9". */
  result_key: string;
  /** The same location for a reader, e.g. "Table 1, row 3 (38292)". */
  result_location: string;
}

export function registerIdentity(v: Pick<SpecVerdict, 'scope' | 'target'>): RegisterIdentity {
  const record = /^record\[(\d+)\]$/.exec(v.scope);
  const prefix = record ? `Record ${Number(record[1]) + 1}, ` : '';
  const t = v.target;
  let where: string;
  if (t.kind === 'table') {
    const label = t.row_label ? ` (${t.row_label})` : '';
    const place = `table ${t.table_index + 1}, row ${t.row_index + 1}${label}`;
    where = prefix ? `${prefix}${place}` : `T${place.slice(1)}`;
  } else {
    where = `${prefix}${t.group} › ${t.cell}`;
  }
  return { result_key: specResultKey(v.scope, v.target), result_location: where };
}

/**
 * One register row per (location, source) — the rule 0105's unique index makes
 * structural, applied in code first so a repeat is dropped rather than failing
 * the whole batch.
 *
 * Deduplicates on IDENTITY, never on value. Two lots that print the same number
 * are two results and both are kept; only the same place on the page judged
 * twice by the same source is one. The engine does not emit that today (it
 * walks each table and row once), so `dropped` is expected to be empty; it is
 * returned rather than swallowed so a producer can say so if that ever changes.
 */
export function uniqueByRegisterIdentity<T extends Pick<SpecVerdict, 'scope' | 'target' | 'source'>>(
  verdicts: T[]
): { kept: T[]; dropped: T[] } {
  const seen = new Set<string>();
  const kept: T[] = [];
  const dropped: T[] = [];
  for (const v of verdicts) {
    const key = `${specResultKey(v.scope, v.target)}::${v.source}`;
    if (seen.has(key)) {
      dropped.push(v);
      continue;
    }
    seen.add(key);
    kept.push(v);
  }
  return { kept, dropped };
}

/**
 * Build the JSON that goes into `document_spec_checks.limit_snapshot`, or NULL
 * when there is nothing to freeze.
 *
 * `limits` is the set of configured limits the verdict was produced from; a
 * verdict whose `limit_id` is not in it falls back to the printed shape rather
 * than inventing numbers.
 */
export function buildLimitSnapshot(
  verdict: SpecVerdict,
  limits: ConfiguredLimit[]
): string | null {
  // `conversion` sits beside the older `unit_equivalence` key rather than
  // replacing it: rows written before it existed carry only the latter, and a
  // reader handles both. It covers sample-basis arithmetic (CFU/100 g → CFU/g)
  // as well as the tenant equivalence, because the SME ruling is that ANY
  // conversion behind a comparison is part of what it was judged against.
  const equated = {
    ...(verdict.unit_equivalence_applied ? { unit_equivalence: 'volume_mass' } : {}),
    ...(verdict.conversion ? { conversion: verdict.conversion } : {}),
  };
  if (verdict.source !== 'limit' || !verdict.limit_id) {
    // A printed-spec verdict's "limit" is the document's own text, which is
    // already captured verbatim in limit_text.
    return verdict.limit_text
      ? JSON.stringify({ printed: verdict.limit_text, ...equated })
      : null;
  }
  const l = limits.find((x) => x.id === verdict.limit_id);
  if (!l) {
    return verdict.limit_text
      ? JSON.stringify({ printed: verdict.limit_text, ...equated })
      : null;
  }
  return JSON.stringify({
    operator: l.operator,
    value_min: l.value_min,
    value_max: l.value_max,
    unit: l.unit,
    // WHICH REVISION judged this. Migration 0085 said the snapshot was
    // "{operator, value_min, value_max, version}" and the version was the one
    // key never actually written — so a reader could see the numbers but not
    // which edition of the limit they came from, which is the entire job of the
    // counter. Now that a version moves only when the threshold semantics move
    // (`limitThresholdChanged`), it is a stable name for the rule that was
    // applied, not a running total of every notes edit. Omitted, never invented,
    // when the loaded row carried none.
    ...(l.version === null || l.version === undefined ? {} : { version: Number(l.version) }),
    severity: l.severity,
    criticality: parseSpecCriticality(l.criticality),
    text: verdict.limit_text,
    ...equated,
    // A supplier watch (0109) is frozen like criticality: whether the tighter
    // limit was inside its review period when this result was judged is part of
    // what it was judged against, and extending the watch later must not
    // rewrite that. Absent = not a watch limit.
    ...(verdict.watch
      ? { supplier_id: l.supplier_id, review_by: verdict.watch.review_by, review_overdue: verdict.watch.review_overdue }
      : {}),
  });
}
